[versions]
paper = "1.20.1-R0.1-SNAPSHOT"
litecommands = "3.10.9"
lombok = "1.18.38"

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
litecommands-bukkit = { module = "dev.rollczi:litecommands-bukkit", version.ref = "litecommands" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
